name: Java CI with Gradle and Checkstyle

on:
  pull_request:
    branches: [ "feature" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: permission for gradlew
        run: chmod u+x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

      # Checkstyle 실행
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      # reviewdog을 사용해 Checkstyle 결과를 PR 리뷰로 추가
      - name: Checkstyle for Java
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          reporter: github-pr-review
          level: warning
